# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{spect}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Clinton R. Nixon"]
  s.date = %q{2010-04-02}
  s.description = %q{An alternate, BDD-inspired, way to write assertions in Ruby that works with Test::Unit and all its kin.}
  s.email = %q{crnixon@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/spect.rb",
     "lib/spect/expectations.rb",
     "lib/spect/expecting.rb",
     "spect.gemspec",
     "test/test_spect.rb"
  ]
  s.homepage = %q{http://github.com/crnixon/spect}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{An alternate, BDD-inspired, way to write assertions in Ruby that works with Test::Unit and all its kin.}
  s.test_files = [
    "test/test_spect.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

